# 24068022 Soh Kai Xuan
# Generated by Django 4.2.23 on 2025-06-23 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('FLOOD', 'Flood'), ('FIRE', 'Fire'), ('EARTHQUAKE', 'Earthquake'), ('LANDSLIDE', 'Landslide'), ('HURRICANE', 'Hurricane'), ('TSUNAMI', 'Tsunami'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(choices=[('FOOD', 'Food'), ('WATER', 'Water'), ('SHELTER', 'Shelter'), ('MEDICAL', 'Medical'), ('RESCUE', 'Rescue'), ('EVACUATION', 'Evacuation'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('people_count', models.PositiveIntegerField(default=1, help_text='Number of people needing aid')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aid_requests', to=settings.AUTH_USER_MODEL)),
                ('disaster_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='disasters.disasterreport')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
