# Generated by Django 4.2.23 on 2025-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerassignment',
            name='volunteer_complete_date',
            field=models.DateTimeField(blank=True, help_text='When the volunteer marked the task as complete', null=True),
        ),
        migrations.AddField(
            model_name='volunteerassignment',
            name='volunteer_start_date',
            field=models.DateTimeField(blank=True, help_text='When the volunteer actually started working on the task', null=True),
        ),
    ]
