# Generated by Django 4.2.23 on 2025-06-23 16:57

from django.db import migrations
from django.contrib.auth import get_user_model
from datetime import datetime


def create_sample_shelters(apps, schema_editor):
    """
    Creates 5 sample shelters for demo purposes
    """
    Shelter = apps.get_model('shelters', 'Shelter')
    
    shelters_data = [
        {
            'name': 'Kuala Lumpur Emergency Shelter',
            'address': '123 Jalan Ampang, Kuala Lumpur, 50450',
            'latitude': 3.157406,
            'longitude': 101.712104,
            'total_capacity': 300,
            'current_occupancy': 125,
            'contact_person': 'Ahmad Bin Abdullah',
            'contact_phone': '012-345-6789',
            'amenities': 'Food service available\nMedical facilities\nPotable water\nBedding\nWashroom facilities\nCharge points for mobile devices',
            'is_active': True,
        },
        {
            'name': 'Penang Flood Relief Center',
            'address': '45 Jalan Bukit, George Town, Penang, 10300',
            'latitude': 5.414476,
            'longitude': 100.329271,
            'total_capacity': 250,
            'current_occupancy': 78,
            'contact_person': 'Lim Wei Ling',
            'contact_phone': '013-987-6543',
            'amenities': 'Food service\nBedding\nWashroom facilities',
            'is_active': True,
        },
        {
            'name': 'Kota Kinabalu Community Center',
            'address': '78 Jalan Tun Fuad, Kota Kinabalu, Sabah, 88000',
            'latitude': 5.980408,
            'longitude': 116.073856,
            'total_capacity': 180,
            'current_occupancy': 180,
            'contact_person': 'Sarah Binti Mohammed',
            'contact_phone': '014-222-3333',
            'amenities': 'Food service\nBasic medical supplies\nBedding\nWashroom facilities\nChildren play area',
            'is_active': True,
        },
        {
            'name': 'Johor Bahru Disaster Relief Hub',
            'address': '22 Jalan Ibrahim, Johor Bahru, 80000',
            'latitude': 1.461546,
            'longitude': 103.761061,
            'total_capacity': 400,
            'current_occupancy': 120,
            'contact_person': 'Tan Mei Ling',
            'contact_phone': '016-555-7777',
            'amenities': 'Food service\nMedical station\nBedding\nWashroom facilities\nPsychological counseling\nWifi available',
            'is_active': True,
        },
        {
            'name': 'Kuching Temporary Housing Center',
            'address': '56 Jalan Borneo, Kuching, Sarawak, 93000',
            'latitude': 1.553110,
            'longitude': 110.345032,
            'total_capacity': 220,
            'current_occupancy': 65,
            'contact_person': 'James Anak Robert',
            'contact_phone': '019-876-5432',
            'amenities': 'Food service\nBedding\nWashroom facilities\nBasic medical supplies',
            'is_active': True,
        },
    ]
    
    for shelter_data in shelters_data:
        Shelter.objects.create(**shelter_data)


def delete_sample_shelters(apps, schema_editor):
    """
    Deletes the sample shelters
    """
    Shelter = apps.get_model('shelters', 'Shelter')
    Shelter.objects.filter(
        name__in=[
            'Kuala Lumpur Emergency Shelter',
            'Penang Flood Relief Center',
            'Kota Kinabalu Community Center',
            'Johor Bahru Disaster Relief Hub',
            'Kuching Temporary Housing Center',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_shelters, delete_sample_shelters),
    ]
